#!/bin/bash
# Copyright (C) 2025 Francesca Spivack
# This program is licensed under the GNU General Public License version 3.
# See the LICENSE file or <https://www.gnu.org/licenses/>.

# Test the output file (output from testsetup, and intended to be run after
# running testsetup)

# Get directory of this script
PARENT_DIR=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
FILENAME="${PARENT_DIR}/out2"

source "$FILENAME"
parse_options "$@"

printf "aa_a is %s\n" "$aa_a"
printf "b is %s\n" "$b"
printf "ccc is %s\n" "$ccc"
printf "d_opt is %s\n" "$d_opt"
printf "e_opt is %s\n" "$e_opt"

printf "\nPositional arguments:\n"
for p in "${positional[@]}"; do
    printf "%s\n" "$p"
done

# Try calling the script with different arguments
# E.g.
# paropts-test-final TEST --ddd "Required option"
# paropts-test-final -a Hello -b -d Test "This is positional arg"
# paropts-test-final -d Test "This is positional arg" -- "Another positional"
# paropts-test-final --help
